alertmanager:
  enabled: false
# prometheus-pushgateway:
#   enabled: false
grafana:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - taxi.aklivity.io
    tls:
      - hosts:
          - taxi.aklivity.io
        secretName: taxi-demo-tls
    path: /grafana
  grafana.ini:
    server:
      domain: taxi.aklivity.io
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      serve_from_sub_path: true
  # additionalDataSources:
  #   - name: Loki
  #     type: loki
  #     url: loki.monitoring.svc.cluster.local:3100

prometheus:
  prometheusSpec:
    replicaExternalLabelName: "__replica__"
    externalLabels: { cluster: "zilla-demos" }
    storagePath: "/data"
    persistentVolume:
      enabled: false
    statefulSet:
      enabled: true
    extraFlags:
      - web.enable-lifecycle
      - storage.tsdb.wal-compression
    remoteWrite:
      - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
        basicAuth:
          username:
            name: remotewrite-secret
            key: username
          password:
            name: remotewrite-secret
            key: password
    remoteWriteDashboards: true
    additionalScrapeConfigs:
      - job_name: zilla
        scrape_interval: 5s
        static_configs:
          - targets: ["zilla.taxi-demo.svc.cluster.local:7190"]
