apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-stack #update your helm deployment name accordingly
  labels:
    app.kubernetes.io/name: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi #update storage level accordingly